"$schema" = 'https://jsr.io/@loading/chat/0.1.16/config-schema.json'

[config]
model = "onnx-community/Llama-3.2-1B-Instruct"
system = [
  "You are an assistant designed to help with any questions the user might have."
]
max_new_tokens = 128
max_length = 20
temperature = 1.0
top_p = 1.0
repetition_penalty = 1.2
